### ISSUE TITLE
Add note about App ID change

### ISSUE THREAD

**Issue by davidolesch** [JackrabbitMobile/WatchToDrone#1]
I changed the App ID so that I could create provisioning profiles under my developer account but didn't know that I had to change the app bundle identifiers in the watch app's and watch app extension's Info.plist.

I would add a note to the "Create an App ID..." instructions to double check that the watch app's Info.plist  has the correct WKCompanionAppBundleIdentifier and that the watch app extension's Info.plist has the correct WKAppBundleIdentifier.

**Comment by mwanninger** [comment]
Good catch, added in 50b3045bffd244cd72f615e5c15c53e40b8d3c40
